import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";
import StickyAudioButton from "./components/ StickyAudioButton";
import DonateFloatingButton from "./components/DonateFloatingButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <a
          href="https://godscoffeecall.com"
          target="_blank"
          rel="noopener noreferrer"
          style={{
            position: "fixed",
            top: "10px",
            left: "10px",
            zIndex: 1000,
            cursor: "pointer",
          }}
        >
          <Image src="/logo/logo.png" alt="God's Coffee Call" width={60} height={60} />
        </a>
        <StickyAudioButton />
        <DonateFloatingButton />
        {children}
      </body>
    </html>
  );
}
